### ISSUE TITLE
Explorer Ads trouble

### ISSUE THREAD

**Issue by lucryptoin** [futurumclix/futurumclix#9] opened 2018-01-28 05:17 UTC
After opening Explorer Ads the progress bar stops and goes error:
We are sorry but this advertisement is no longer available.
The same error on the demo script.
Below the error log.

2018-01-28 05:05:11 Error: [BadRequestException] Please do not refresh page after certain actions like buying on the site etc. Please come back to previous page with the back button in web browser.
Request URL: /explorer_ads/next_subpage/5a6bc07a-45c4-4975-8675-4e6ac6367471
Stack Trace:
#0 [internal function]: AppController->_badRequest('auth')
#1 /lib/Cake/Controller/Component/SecurityComponent.php(831): call_user_func_array(Array, Array)
#2 /lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(ExplorerAdsController), '_badRequest', Array)
#3 /lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(ExplorerAdsController), 'auth', Object(AuthSecurityException))
#4 [internal function]: SecurityComponent->startup(Object(ExplorerAdsController))
#5 /lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ExplorerAdsController), Object(CakeRequest))
#11 /app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by futurumclix** [comment] 2018-01-28 11:20
This error means form (security token) was submitted twice. Are you using custom theme?

**Comment by lucryptoin** [comment] 2018-01-28 12:07
It is in Fresh template. In your demo too. How to fix?

**Comment by futurumclix** [comment] 2018-01-28 14:27
I also encountered similar (from the user's point of view) error caused by not accurate time measurement in JS part of Explorer Ads surfer. If you are interested, it was fixed in commit 7a1a212.

**Comment by futurumclix** [comment] 2018-01-28 14:28
Let me know if those changes fixes your issue.

**Comment by lucryptoin** [comment] 2018-01-28 15:01
I have updated these two files.
The progress bar started to work with message: Please wait for the site validation. 
Then the progress bar stopped, and again: We are sorry but this advertisement is no longer available.

**Comment by lucryptoin** [comment] 2018-01-28 15:04
Maybe it's related. But the report button is also not working. Doesn't open modal window.

**Comment by futurumclix** [comment] 2018-01-28 15:06
Did you also make fixes in theme? For your issue most important is commit 7b26236.

**Comment by lucryptoin** [comment] 2018-01-28 15:10
Now everything is working fine, thanks!

**Closed** 2018-01-28 15:18 UTC
