### ISSUE TITLE
Help with installation (I can pay)

### ISSUE THREAD

**Issue by shamuel22** [futurumclix/futurumclix#30] opened 2018-03-05 22:20 UTC
Pls I need help with installation.  I can make a donacion via BTC @futurumclix

**Comment by alexistdev** [comment] 2018-03-06 05:18
its very simple, just download the package which is include with the cake package:
https://github.com/futurumclix/futurumclix/releases

download the latest version futurumclix-1.7.2.zip , and extract on your root panel (public_html)
then access your site, and follow the installation step by step.  Done.

**Comment by shamuel22** [comment] 2018-03-06 12:55
![36950104-7cf7aa9c-1fc7-11e8-86fc-f58bc0233d6d](https://user-images.githubusercontent.com/16228257/37033361-26bc715c-211c-11e8-901e-0ac1c1d97b28.png)

**Comment by alexistdev** [comment] 2018-03-06 14:08
check your hosting server, was mod_rewrite module had been enabled or not?

**Comment by shamuel22** [comment] 2018-03-06 20:55
Yes mod_rewrite is enable in my server

**Comment by futurumclix** [comment] 2018-03-19 22:18
This is a duplicate of #26 so I will close this one. @shamuel22 please answer in #26, I will try to debug that.

**Closed by futurumclix** 2018-03-19 22:18 UTC
